experiment_name: "model_a_hf_demo"

data:
  dataset_type: "hf" # Use the Hugging Face dataset loader
  dataset_name: "itsanmolgupta/mimic-cxr-dataset"
  batch_size: 2
  num_workers: 0
  image_size: 224

model:
  vision_backbone: "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
  text_backbone: "hf-hub:microsoft/BiomedCLIP-PubMedBERT_256-vit_base_patch16_224"
  mask_ratio: 0.5
  temperature: 0.1
  use_masking: false
  use_sparsity_loss: false

training:
  epochs: 2
  lr: 1.0e-4
  weight_decay: 0.01
  warmup_steps: 1
  print_freq: 1
  device: "mps"
  use_amp: false

wandb:
  enable: false
